cp ~/gits/network-inventory-yang/yang/ietf-network-inventory.yang net-inv
cp ~/gits/network-inventory-topology/yang/ietf-network-inventory-topology.yang net-inv
cp ~/gits/network-inventory-location/ietf-ni-location.yang net-inv
cp ~/gits/network-inventory-software/ietf-network-inventory-sw-ext.yang net-inv
cp ~/gits/yang/standard/ietf/RFC/iana-hardware.yang net-inv
cp ~/gits/yang/standard/ietf/RFC/ietf-yang-types.yang net-inv
cp ~/gits/yang/standard/ietf/RFC/ietf-inet-types.yang net-inv
cp ~/gits/yang/standard/ietf/RFC/ietf-network.yang net-inv
cp ~/gits/yang/standard/ietf/RFC/ietf-network-topology.yang net-inv
cp ~/gits/yang/standard/ietf/RFC/ietf-geo-location.yang net-inv
